name: Deploy to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v3
        with:
          path: '.jampack'
          key: jampack-${{ github.run_id }}
          restore-keys: |
            jampack
      - name: Set up Pages
        uses: actions/configure-pages@v5
      - name: Optimize with Jampack
        run: npx @divriots/jampack .
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftps
          server-dir: ${{ secrets.ftp_server_dir }}
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.jampack*
            **/.jampack/**
            **/_jampack*
            **/_jampack/**
